on:
  release:
    types: [published]

jobs:
  release-linux-amd64:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find: '__version__ = ".+"'
        replace: '__version__ = "${{ github.ref_name }}"'
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ghcr.io/garmin-connect-prom-exporter
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
